language: python
sudo: required
dist: xenial

python:
  - '3.6'
  - "3.7"
  - "3.8-dev"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  # Start the python web server to test against
  - cd example && sudo python -m SimpleHTTPServer 80 &
  # Start Chrome
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  # Install the Chrome Driver according to the Spliter Docs
  - wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - mkdir -p $HOME/bin
  - mv chromedriver $HOME/bin
  - echo "export PATH=$PATH:$HOME/bin" >> $HOME/.bash_profile
  - source ~/.bash_profile
  # Map www to localhost to mock docker doing it.
  - echo "127.0.0.1       www" | sudo tee -a /etc/hosts

install:
  - pip install -r dev-requirements.txt

script:
  - flake8
  - (cd docs && make html)
  # TODO: Optimize this command. It's wonky right now.
  - PYTHONPATH=`pwd`/veripy:$PYTHONPATH behave veripy/features/

# TODO: We don't have coveralls yet.
# after_success: coveralls
