language: python
python:
  - '3.6'
  - "3.7-dev"  # 3.7 development branch

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - pip install -r dev-requirements.txt

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - flake8
  # TODO: Optimize this command. It's wonky right now.
  - PYTHONPATH=`pwd`/veripy:$PYTHONPATH behave veripy/features/

# TODO: We don't have coveralls yet.
# after_success: coveralls
