language: python
sudo: required

python:
  - '3.6'
  - "3.7"
  - "3.8-dev"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  # Install the Chrome Driver according to the Spliter Docs
  - wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - mkdir -p $HOME/bin
  - mv chromedriver $HOME/bin
  - echo "export PATH=$PATH:$HOME/bin" >> $HOME/.bash_profile
  - source ~/.bash_profile

install:
  - pip install -r dev-requirements.txt

script:
  - flake8
  # TODO: Optimize this command. It's wonky right now.
  - PYTHONPATH=`pwd`/veripy:$PYTHONPATH behave veripy/features/

# TODO: We don't have coveralls yet.
# after_success: coveralls
