version: "3.7"

services:
  www:
    image: nginx:1.13.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./example/sampleapp/nginx-services.conf:/etc/nginx/conf.d/default.conf
      - ./example/sampleapp:/var/www/public
      - ./reports/reports:/var/www/public/reports
      - ./docs/_build/html:/var/www/public/docs/

  veripy:
    build:
      context: .
      target: development
    environment:
      - BROWSER=remote
      - SELENIUM_URL=http://browser:4444/wd/hub
      - ENVIRONMENT=dev
      - REPORTS_DIR=/app/example/reports
      - FIXTURES_DIR=/app/example/fixtures
      - RESOURCES_DIR=/app/example/resources
    volumes:
      - ./example:/app/example
      - ./veripy:/app/veripy

  #
  # Browser virtualization integration testing
  #
  browser:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      # Location to use for browsing for files to upload via browser
      - ./example/resources:/e2e/uploads
      # Shared memory, selenium recommends using host's shared memory or setting to 2gb
      - /dev/shm:/dev/shm
