version: "3"

services:
  www:
    image: nginx:1.13.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./example/nginx-services.conf:/etc/nginx/conf.d/default.conf
      - ./example:/var/www/public
      - ./reports:/var/www/public/reports
      - ./docs/_build/html:/var/www/public/docs/

  veripy:
    build: .
    environment:
      - BROWSER=remote
      - SELENIUM_URL=http://selenium_hub:4444/wd/hub
      - ENVIRONMENT=dev
      - PYTHONPATH=/app/veripy/
    depends_on:
      - www
      - selenium_hub
    volumes:
      - ./reports:/app/reports
      - ./veripy:/app/veripy
    links:
      - selenium_hub:selenium_hub

  #
  # Browser virtualization integration testing
  #
  selenium_hub:
    image: selenium/standalone-chrome-debug
    privileged: true
    depends_on:
      - www
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - "uploads:/uploads"
volumes:
  uploads:
