import logging
from behave import then

logger = logging.getLogger('capture')


@then('write the "{element_name}" generated by the system')
@then('write down the value of "{element_name}"')
def capture_element_text(context, element_name):
    """ Given an element, record the value of the element for later display
    in the report.

    ::

        Then write the "{element}" generated by the system.
        Then write down the value of "{element}".

    """
    logger.info(f'Capturing content from  "{element_name}"')
    try:
        text = context.page[element_name].text
    except context.page.ElementNotFound:
        raise AssertionError(f'The {element_name} was not found on the page')
    context.step.stored_value = text
