@fixture.browser.chrome
Feature: Capture Sentences
    Capture sentences allow the Tester to capture either screenshots or data
    from the page and record it to the report


    @example_app @capture @capture_content
    Scenario: Test that the user can capture content that is on the page
        Given that the browser is at "localhost-hello"
        Then write the "Random Number" generated by the system
        And take a screen shot


    @example_app @capture @capture_screenshot
    Scenario: Test that the user can capture a screenshot of the page
        Given that the browser is at "localhost-hello"
        And the browser window is 800 by 600 pixels
        Then take a screen shot

    @example_app @capture @capture_screenshot @prompt @fixture.browser.chrome
    Scenario: Test that the capture gracefully fails when there is an alert
        Given that the browser is at "localhost-hello"
        And the browser window is 800 by 600 pixels
        When the user clicks the "Confirm Prompt Button"
        Then the statement that 'take a screen shot' responds with
            """
            Capturing a screenshot of a browser alert is not supported.
            """
